spring:
  datasource:
    url: jdbc:mysql://localhost:3306/weather
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: weather
    password: weather
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
