spring:
  datasource:
    url: jdbc:mysql://localhost:3306/weather_predictionmarkets?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      transaction-isolation: TRANSACTION_READ_COMMITTED
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
